language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
after_success:
    - coverallslanguage: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
script:
    - py.test